/* Generated By:JavaCC: Do not edit this line. JSPConstants.java */
public interface JSPConstants {

  int EOF = 0;
  int CONSTANT = 5;
  int DIGIT = 6;
  int DELETE = 7;
  int FUNCTION = 8;
  int IN = 9;
  int CASE = 10;
  int NEW = 11;
  int RETURN = 12;
  int THIS = 13;
  int TYPEOF = 14;
  int VOID = 15;
  int WITH = 16;
  int CATCH = 17;
  int CLASS = 18;
  int CONST = 19;
  int DEBUGGER = 20;
  int _DEFAULT = 21;
  int ENUM = 22;
  int EXPORT = 23;
  int EXTENDS = 24;
  int FINALLY = 25;
  int IMPORT = 26;
  int SUPER = 27;
  int SWITCH = 28;
  int THROW = 29;
  int TRY = 30;
  int VAR = 31;
  int BREAK = 32;
  int CONTINUE = 33;
  int IF = 34;
  int ELSE = 35;
  int DO = 36;
  int WHILE = 37;
  int FOR = 38;
  int LEFTBRACE = 39;
  int RIGHTBRACE = 40;
  int LEFTPAREN = 41;
  int RIghtPAREN = 42;
  int LEFTBRACKET = 43;
  int RIGHTBRACKET = 44;
  int DOT = 45;
  int SEMICOLON = 46;
  int COMMA = 47;
  int Less_than = 48;
  int Greater_than = 49;
  int Less_than_or_Equal = 50;
  int Greater_than_or_Equal = 51;
  int EQ = 52;
  int Not_equal = 53;
  int Strict_Equals_Operator = 54;
  int Strict_Does_not_equal_Operator = 55;
  int EOL = 56;
  int MOD = 57;
  int NOT = 58;
  int DIVIDE = 59;
  int PLUS = 60;
  int MINUS = 61;
  int MULTIPLY = 62;
  int INCR = 63;
  int DECR = 64;
  int LSHIFT = 65;
  int RSHIFT = 66;
  int RUNSHIFT = 67;
  int BIT_AND = 68;
  int BIT_OR = 69;
  int XOR = 70;
  int TILDE = 71;
  int SC_AND = 72;
  int SC_OR = 73;
  int HOOK = 74;
  int COLON = 75;
  int ASSIGN = 76;
  int PLUSASSIGN = 77;
  int MINUSASSIGN = 78;
  int STARASSIGN = 79;
  int REMASSIGN = 80;
  int LSHIFTASSIGN = 81;
  int RSIGNEDSHIFTASSIGN = 82;
  int RUNSIGNEDSHIFTASSIGN = 83;
  int ANDASSIGN = 84;
  int ORASSIGN = 85;
  int XORASSIGN = 86;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<CONSTANT>",
    "<DIGIT>",
    "\"delete\"",
    "\"function\"",
    "\"in\"",
    "\"case\"",
    "\"new\"",
    "\"return\"",
    "\"this\"",
    "\"typeof\"",
    "\"void\"",
    "\"with\"",
    "\"catch\"",
    "\"class\"",
    "\"const\"",
    "\"debugger\"",
    "\"default\"",
    "\"enum\"",
    "\"export\"",
    "\"extends\"",
    "\"finally\"",
    "\"import\"",
    "\"super\"",
    "\"switch\"",
    "\"throw\"",
    "\"try\"",
    "\"var\"",
    "\"break\"",
    "\"continue\"",
    "\"if\"",
    "\"else\"",
    "\"do\"",
    "\"while\"",
    "\"for\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\";\"",
    "\",\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"===\"",
    "\"!==\"",
    "<EOL>",
    "\"%\"",
    "\"!\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"++\"",
    "\"--\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"~\"",
    "\"&&\"",
    "\"||\"",
    "\"?\"",
    "\":\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
  };

}
