/* Generated By:JavaCC: Do not edit this line. JSConstants.java */
public interface JSConstants {

  int EOF = 0;
  int FOR = 9;
  int WHILE = 10;
  int DO = 11;
  int VAR = 12;
  int IF = 13;
  int ELSE = 14;
  int ELSEIF = 15;
  int TRUE = 16;
  int FALSE = 17;
  int CONTINUE = 18;
  int BREAK = 19;
  int RETURN = 20;
  int STOP = 21;
  int FUNCTION = 22;
  int NEW = 23;
  int SEMICOLON = 24;
  int NUM = 25;
  int PRINT = 26;
  int READ = 27;
  int SIN = 28;
  int COS = 29;
  int DIGIT = 30;
  int CHARACTER = 31;
  int ID = 32;
  int String = 33;

  int DEFAULT = 0;
  int COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 5>",
    "\"/*\"",
    "<token of kind 7>",
    "\"*/\"",
    "\"for\"",
    "\"while\"",
    "\"do\"",
    "\"var\"",
    "\"if\"",
    "\"else\"",
    "<ELSEIF>",
    "\"true\"",
    "\"false\"",
    "\"continue\"",
    "\"break\"",
    "\"return\"",
    "<STOP>",
    "\"function\"",
    "\"new\"",
    "\";\"",
    "<NUM>",
    "\"print\"",
    "\"read\"",
    "\"sin\"",
    "\"cos\"",
    "<DIGIT>",
    "<CHARACTER>",
    "<ID>",
    "<String>",
    "\"[\"",
    "\"]\"",
    "<token of kind 36>",
    "\"==\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"&&\"",
    "\"/\"",
    "\"^\"",
    "\"%\"",
    "\"!\"",
    "\",\"",
    "\".\"",
    "\"++\"",
    "\"--\"",
    "\"{\"",
    "\"}\"",
  };

}
